/*
    ChibiOS - Copyright (C) 2006..2016 Giovanni Di Sirio
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

/*
    Generated by gen-board.h.py based on cfg/board.yaml
*/

#ifndef _BOARD_H_
#define _BOARD_H_


/*
    Setup for AGC/DSKY Emulator
*/

/*
    Board identifier
*/
#define BOARD_AGC_DSKY_EMULATOR
#define BOARD_NAME                     "AGC/DSKY Emulator"

/*
    Board oscillators-related settings.
*/
#if !defined(STM32_LSECLK)
#define STM32_LSECLK                   0U
#endif

#if !defined(STM32_HSECLK)
#define STM32_HSECLK                   0U
#endif

/*
    Board voltages
    Required for performance limits calculation.
*/
#define STM32_VDD                      330U

/*
    MCU type as defined in the ST header.
*/
#define STM32F072xB

/*
    Other settings.
*/
#define STM32_HSE_BYPASS               
#define STM32_LSEDRV                   (3U << 3U)

/*
    IO pins assignments.
*/
#define GPIOA_NCS_2                    0U
#define GPIOA_NRST_2                   1U
#define GPIOA_USART_TX                 2U
#define GPIOA_USART_RX                 3U
#define GPIOA_PIN4                     4U
#define GPIOA_SPI1_SCK                 5U
#define GPIOA_SPI1_MISO                6U
#define GPIOA_SPI1_MOSI                7U
#define GPIOA_CO5                      8U
#define GPIOA_BR2                      9U
#define GPIOA_BR4                      10U
#define GPIOA_USB_DM                   11U
#define GPIOA_USB_DP                   12U
#define GPIOA_SWDIO                    13U
#define GPIOA_SWCLK                    14U
#define GPIOA_BR3                      15U

#define GPIOB_PIN0                     0U
#define GPIOB_PIN1                     1U
#define GPIOB_NCS_3                    2U
#define GPIOB_BC3                      3U
#define GPIOB_BC1                      4U
#define GPIOB_BC2                      5U
#define GPIOB_BC4                      6U
#define GPIOB_BC5                      7U
#define GPIOB_PIN8                     8U
#define GPIOB_PIN9                     9U
#define GPIOB_NRST_3                   10U
#define GPIOB_CO8                      11U
#define GPIOB_NCS_MPU                  12U
#define GPIOB_SPI2_SCK                 13U
#define GPIOB_SPI2_MISO                14U
#define GPIOB_SPI2_MOSI                15U

#define GPIOC_NCS_1                    0U
#define GPIOC_NRST_1                   1U
#define GPIOC_PIN2                     2U
#define GPIOC_PIN3                     3U
#define GPIOC_PIN4                     4U
#define GPIOC_PIN5                     5U
#define GPIOC_CO1                      6U
#define GPIOC_CO2                      7U
#define GPIOC_CO3                      8U
#define GPIOC_CO4                      9U
#define GPIOC_BR1                      10U
#define GPIOC_PIN11                    11U
#define GPIOC_PIN12                    12U
#define GPIOC_LED_DIN                  13U
#define GPIOC_CO7                      14U
#define GPIOC_CO6                      15U

#define GPIOD_PIN0                     0U
#define GPIOD_PIN1                     1U
#define GPIOD_PIN2                     2U
#define GPIOD_PIN3                     3U
#define GPIOD_PIN4                     4U
#define GPIOD_PIN5                     5U
#define GPIOD_PIN6                     6U
#define GPIOD_PIN7                     7U
#define GPIOD_PIN8                     8U
#define GPIOD_PIN9                     9U
#define GPIOD_PIN10                    10U
#define GPIOD_PIN11                    11U
#define GPIOD_PIN12                    12U
#define GPIOD_PIN13                    13U
#define GPIOD_PIN14                    14U
#define GPIOD_PIN15                    15U

#define GPIOE_PIN0                     0U
#define GPIOE_PIN1                     1U
#define GPIOE_PIN2                     2U
#define GPIOE_PIN3                     3U
#define GPIOE_PIN4                     4U
#define GPIOE_PIN5                     5U
#define GPIOE_PIN6                     6U
#define GPIOE_PIN7                     7U
#define GPIOE_PIN8                     8U
#define GPIOE_PIN9                     9U
#define GPIOE_PIN10                    10U
#define GPIOE_PIN11                    11U
#define GPIOE_PIN12                    12U
#define GPIOE_PIN13                    13U
#define GPIOE_PIN14                    14U
#define GPIOE_PIN15                    15U

#define GPIOF_PIN0                     0U
#define GPIOF_PIN1                     1U
#define GPIOF_PIN2                     2U
#define GPIOF_PIN3                     3U
#define GPIOF_PIN4                     4U
#define GPIOF_PIN5                     5U
#define GPIOF_PIN6                     6U
#define GPIOF_PIN7                     7U
#define GPIOF_PIN8                     8U
#define GPIOF_PIN9                     9U
#define GPIOF_PIN10                    10U
#define GPIOF_PIN11                    11U
#define GPIOF_PIN12                    12U
#define GPIOF_PIN13                    13U
#define GPIOF_PIN14                    14U
#define GPIOF_PIN15                    15U

/*
    IO lines assignments.
*/
#define LINE_BC1                       PAL_LINE(GPIOB, 4U)
#define LINE_BC2                       PAL_LINE(GPIOB, 5U)
#define LINE_BC3                       PAL_LINE(GPIOB, 3U)
#define LINE_BC4                       PAL_LINE(GPIOB, 6U)
#define LINE_BC5                       PAL_LINE(GPIOB, 7U)
#define LINE_BR1                       PAL_LINE(GPIOC, 10U)
#define LINE_BR2                       PAL_LINE(GPIOA, 9U)
#define LINE_BR3                       PAL_LINE(GPIOA, 15U)
#define LINE_BR4                       PAL_LINE(GPIOA, 10U)
#define LINE_CO1                       PAL_LINE(GPIOC, 6U)
#define LINE_CO2                       PAL_LINE(GPIOC, 7U)
#define LINE_CO3                       PAL_LINE(GPIOC, 8U)
#define LINE_CO4                       PAL_LINE(GPIOC, 9U)
#define LINE_CO5                       PAL_LINE(GPIOA, 8U)
#define LINE_CO6                       PAL_LINE(GPIOC, 15U)
#define LINE_CO7                       PAL_LINE(GPIOC, 14U)
#define LINE_CO8                       PAL_LINE(GPIOB, 11U)
#define LINE_LED_DIN                   PAL_LINE(GPIOC, 13U)
#define LINE_NCS_1                     PAL_LINE(GPIOC, 0U)
#define LINE_NCS_2                     PAL_LINE(GPIOA, 0U)
#define LINE_NCS_3                     PAL_LINE(GPIOB, 2U)
#define LINE_NCS_MPU                   PAL_LINE(GPIOB, 12U)
#define LINE_NRST_1                    PAL_LINE(GPIOC, 1U)
#define LINE_NRST_2                    PAL_LINE(GPIOA, 1U)
#define LINE_NRST_3                    PAL_LINE(GPIOB, 10U)
#define LINE_SPI1_MISO                 PAL_LINE(GPIOA, 6U)
#define LINE_SPI1_MOSI                 PAL_LINE(GPIOA, 7U)
#define LINE_SPI1_SCK                  PAL_LINE(GPIOA, 5U)
#define LINE_SPI2_MISO                 PAL_LINE(GPIOB, 14U)
#define LINE_SPI2_MOSI                 PAL_LINE(GPIOB, 15U)
#define LINE_SPI2_SCK                  PAL_LINE(GPIOB, 13U)
#define LINE_SWCLK                     PAL_LINE(GPIOA, 14U)
#define LINE_SWDIO                     PAL_LINE(GPIOA, 13U)
#define LINE_USART_RX                  PAL_LINE(GPIOA, 3U)
#define LINE_USART_TX                  PAL_LINE(GPIOA, 2U)
#define LINE_USB_DM                    PAL_LINE(GPIOA, 11U)
#define LINE_USB_DP                    PAL_LINE(GPIOA, 12U)

/*
    I/O ports initial setup, this configuration is established soon after reset
    in the initialization code.
     Please refer to the STM32 Reference Manual for details.
*/
#define PIN_MODE_INPUT(n)              (0U << ((n) * 2U))
#define PIN_MODE_OUTPUT(n)             (1U << ((n) * 2U))
#define PIN_MODE_ALTERNATE(n)          (2U << ((n) * 2U))
#define PIN_MODE_ANALOG(n)             (3U << ((n) * 2U))
#define PIN_OD_LOW(n)                  (0U << (n))
#define PIN_OD_HIGH(n)                 (1U << (n))
#define PIN_OTYPE_PUSHPULL(n)          (0U << (n))
#define PIN_OTYPE_OPENDRAIN(n)         (1U << (n))
#define PIN_OSPEED_VERYLOW(n)          (0U << ((n) * 2U))
#define PIN_OSPEED_LOW(n)              (1U << ((n) * 2U))
#define PIN_OSPEED_MEDIUM(n)           (2U << ((n) * 2U))
#define PIN_OSPEED_HIGH(n)             (3U << ((n) * 2U))
#define PIN_PUPD_FLOATING(n)           (0U << ((n) * 2U))
#define PIN_PUPD_PULLUP(n)             (1U << ((n) * 2U))
#define PIN_PUPD_PULLDOWN(n)           (2U << ((n) * 2U))
#define PIN_AFIO_AF(n, v)              ((v) << (((n) % 8U) * 4U))

/*
 *  GPIOA setup:
 *
 * PA0  - NCS_2                        (output floating).
 * PA1  - NRST_2                       (output floating).
 * PA2  - USART_TX                     (af1 floating).
 * PA3  - USART_RX                     (af1 floating).
 * PA4  - PIN4                         (unused).
 * PA5  - SPI1_SCK                     (af0 floating).
 * PA6  - SPI1_MISO                    (af0 floating).
 * PA7  - SPI1_MOSI                    (af0 floating).
 * PA8  - CO5                          (output startlow floating).
 * PA9  - BR2                          (output startlow floating).
 * PA10 - BR4                          (output startlow floating).
 * PA11 - USB_DM                       (af0).
 * PA12 - USB_DP                       (af0).
 * PA13 - SWDIO                        (af0).
 * PA14 - SWCLK                        (af0 pulldown).
 * PA15 - BR3                          (output startlow floating).
*/
#define VAL_GPIOA_MODER                (PIN_MODE_OUTPUT(GPIOA_NCS_2) | \
                                        PIN_MODE_OUTPUT(GPIOA_NRST_2) | \
                                        PIN_MODE_ALTERNATE(GPIOA_USART_TX) | \
                                        PIN_MODE_ALTERNATE(GPIOA_USART_RX) | \
                                        PIN_MODE_INPUT(GPIOA_PIN4) | \
                                        PIN_MODE_ALTERNATE(GPIOA_SPI1_SCK) | \
                                        PIN_MODE_ALTERNATE(GPIOA_SPI1_MISO) | \
                                        PIN_MODE_ALTERNATE(GPIOA_SPI1_MOSI) | \
                                        PIN_MODE_OUTPUT(GPIOA_CO5) | \
                                        PIN_MODE_OUTPUT(GPIOA_BR2) | \
                                        PIN_MODE_OUTPUT(GPIOA_BR4) | \
                                        PIN_MODE_ALTERNATE(GPIOA_USB_DM) | \
                                        PIN_MODE_ALTERNATE(GPIOA_USB_DP) | \
                                        PIN_MODE_ALTERNATE(GPIOA_SWDIO) | \
                                        PIN_MODE_ALTERNATE(GPIOA_SWCLK) | \
                                        PIN_MODE_OUTPUT(GPIOA_BR3))

#define VAL_GPIOA_OTYPER               (PIN_OTYPE_PUSHPULL(GPIOA_NCS_2) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_NRST_2) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_USART_TX) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_USART_RX) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_PIN4) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_SPI1_SCK) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_SPI1_MISO) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_SPI1_MOSI) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_CO5) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_BR2) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_BR4) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_USB_DM) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_USB_DP) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_SWDIO) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_SWCLK) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_BR3))

#define VAL_GPIOA_OSPEEDR              (PIN_OSPEED_HIGH(GPIOA_NCS_2) | \
                                        PIN_OSPEED_HIGH(GPIOA_NRST_2) | \
                                        PIN_OSPEED_HIGH(GPIOA_USART_TX) | \
                                        PIN_OSPEED_HIGH(GPIOA_USART_RX) | \
                                        PIN_OSPEED_HIGH(GPIOA_PIN4) | \
                                        PIN_OSPEED_HIGH(GPIOA_SPI1_SCK) | \
                                        PIN_OSPEED_HIGH(GPIOA_SPI1_MISO) | \
                                        PIN_OSPEED_HIGH(GPIOA_SPI1_MOSI) | \
                                        PIN_OSPEED_HIGH(GPIOA_CO5) | \
                                        PIN_OSPEED_HIGH(GPIOA_BR2) | \
                                        PIN_OSPEED_HIGH(GPIOA_BR4) | \
                                        PIN_OSPEED_HIGH(GPIOA_USB_DM) | \
                                        PIN_OSPEED_HIGH(GPIOA_USB_DP) | \
                                        PIN_OSPEED_HIGH(GPIOA_SWDIO) | \
                                        PIN_OSPEED_HIGH(GPIOA_SWCLK) | \
                                        PIN_OSPEED_HIGH(GPIOA_BR3))

#define VAL_GPIOA_PUPDR                (PIN_PUPD_FLOATING(GPIOA_NCS_2) | \
                                        PIN_PUPD_FLOATING(GPIOA_NRST_2) | \
                                        PIN_PUPD_FLOATING(GPIOA_USART_TX) | \
                                        PIN_PUPD_FLOATING(GPIOA_USART_RX) | \
                                        PIN_PUPD_PULLUP(GPIOA_PIN4) | \
                                        PIN_PUPD_FLOATING(GPIOA_SPI1_SCK) | \
                                        PIN_PUPD_FLOATING(GPIOA_SPI1_MISO) | \
                                        PIN_PUPD_FLOATING(GPIOA_SPI1_MOSI) | \
                                        PIN_PUPD_FLOATING(GPIOA_CO5) | \
                                        PIN_PUPD_FLOATING(GPIOA_BR2) | \
                                        PIN_PUPD_FLOATING(GPIOA_BR4) | \
                                        PIN_PUPD_PULLUP(GPIOA_USB_DM) | \
                                        PIN_PUPD_PULLUP(GPIOA_USB_DP) | \
                                        PIN_PUPD_PULLUP(GPIOA_SWDIO) | \
                                        PIN_PUPD_PULLDOWN(GPIOA_SWCLK) | \
                                        PIN_PUPD_FLOATING(GPIOA_BR3))

#define VAL_GPIOA_ODR                  (PIN_OD_HIGH(GPIOA_NCS_2) | \
                                        PIN_OD_HIGH(GPIOA_NRST_2) | \
                                        PIN_OD_HIGH(GPIOA_USART_TX) | \
                                        PIN_OD_HIGH(GPIOA_USART_RX) | \
                                        PIN_OD_HIGH(GPIOA_PIN4) | \
                                        PIN_OD_HIGH(GPIOA_SPI1_SCK) | \
                                        PIN_OD_HIGH(GPIOA_SPI1_MISO) | \
                                        PIN_OD_HIGH(GPIOA_SPI1_MOSI) | \
                                        PIN_OD_LOW(GPIOA_CO5) | \
                                        PIN_OD_LOW(GPIOA_BR2) | \
                                        PIN_OD_LOW(GPIOA_BR4) | \
                                        PIN_OD_HIGH(GPIOA_USB_DM) | \
                                        PIN_OD_HIGH(GPIOA_USB_DP) | \
                                        PIN_OD_HIGH(GPIOA_SWDIO) | \
                                        PIN_OD_HIGH(GPIOA_SWCLK) | \
                                        PIN_OD_LOW(GPIOA_BR3))

#define VAL_GPIOA_AFRL                 (PIN_AFIO_AF(GPIOA_NCS_2, 0U) | \
                                        PIN_AFIO_AF(GPIOA_NRST_2, 0U) | \
                                        PIN_AFIO_AF(GPIOA_USART_TX, 1U) | \
                                        PIN_AFIO_AF(GPIOA_USART_RX, 1U) | \
                                        PIN_AFIO_AF(GPIOA_PIN4, 0U) | \
                                        PIN_AFIO_AF(GPIOA_SPI1_SCK, 0U) | \
                                        PIN_AFIO_AF(GPIOA_SPI1_MISO, 0U) | \
                                        PIN_AFIO_AF(GPIOA_SPI1_MOSI, 0U))

#define VAL_GPIOA_AFRH                 (PIN_AFIO_AF(GPIOA_CO5, 0U) | \
                                        PIN_AFIO_AF(GPIOA_BR2, 0U) | \
                                        PIN_AFIO_AF(GPIOA_BR4, 0U) | \
                                        PIN_AFIO_AF(GPIOA_USB_DM, 0U) | \
                                        PIN_AFIO_AF(GPIOA_USB_DP, 0U) | \
                                        PIN_AFIO_AF(GPIOA_SWDIO, 0U) | \
                                        PIN_AFIO_AF(GPIOA_SWCLK, 0U) | \
                                        PIN_AFIO_AF(GPIOA_BR3, 0U))

/*
 *  GPIOB setup:
 *
 * PB0  - PIN0                         (unused).
 * PB1  - PIN1                         (unused).
 * PB2  - NCS_3                        (output floating).
 * PB3  - BC3                          (pulldown).
 * PB4  - BC1                          (pulldown).
 * PB5  - BC2                          (pulldown).
 * PB6  - BC4                          (pulldown).
 * PB7  - BC5                          (pulldown).
 * PB8  - PIN8                         (unused).
 * PB9  - PIN9                         (unused).
 * PB10 - NRST_3                       (output floating).
 * PB11 - CO8                          (output startlow floating).
 * PB12 - NCS_MPU                      (af0 floating).
 * PB13 - SPI2_SCK                     (af0 floating).
 * PB14 - SPI2_MISO                    (af0 floating).
 * PB15 - SPI2_MOSI                    (af0 floating).
*/
#define VAL_GPIOB_MODER                (PIN_MODE_INPUT(GPIOB_PIN0) | \
                                        PIN_MODE_INPUT(GPIOB_PIN1) | \
                                        PIN_MODE_OUTPUT(GPIOB_NCS_3) | \
                                        PIN_MODE_INPUT(GPIOB_BC3) | \
                                        PIN_MODE_INPUT(GPIOB_BC1) | \
                                        PIN_MODE_INPUT(GPIOB_BC2) | \
                                        PIN_MODE_INPUT(GPIOB_BC4) | \
                                        PIN_MODE_INPUT(GPIOB_BC5) | \
                                        PIN_MODE_INPUT(GPIOB_PIN8) | \
                                        PIN_MODE_INPUT(GPIOB_PIN9) | \
                                        PIN_MODE_OUTPUT(GPIOB_NRST_3) | \
                                        PIN_MODE_OUTPUT(GPIOB_CO8) | \
                                        PIN_MODE_ALTERNATE(GPIOB_NCS_MPU) | \
                                        PIN_MODE_ALTERNATE(GPIOB_SPI2_SCK) | \
                                        PIN_MODE_ALTERNATE(GPIOB_SPI2_MISO) | \
                                        PIN_MODE_ALTERNATE(GPIOB_SPI2_MOSI))

#define VAL_GPIOB_OTYPER               (PIN_OTYPE_PUSHPULL(GPIOB_PIN0) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_PIN1) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_NCS_3) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_BC3) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_BC1) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_BC2) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_BC4) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_BC5) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_PIN8) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_PIN9) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_NRST_3) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_CO8) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_NCS_MPU) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_SPI2_SCK) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_SPI2_MISO) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_SPI2_MOSI))

#define VAL_GPIOB_OSPEEDR              (PIN_OSPEED_HIGH(GPIOB_PIN0) | \
                                        PIN_OSPEED_HIGH(GPIOB_PIN1) | \
                                        PIN_OSPEED_HIGH(GPIOB_NCS_3) | \
                                        PIN_OSPEED_HIGH(GPIOB_BC3) | \
                                        PIN_OSPEED_HIGH(GPIOB_BC1) | \
                                        PIN_OSPEED_HIGH(GPIOB_BC2) | \
                                        PIN_OSPEED_HIGH(GPIOB_BC4) | \
                                        PIN_OSPEED_HIGH(GPIOB_BC5) | \
                                        PIN_OSPEED_HIGH(GPIOB_PIN8) | \
                                        PIN_OSPEED_HIGH(GPIOB_PIN9) | \
                                        PIN_OSPEED_HIGH(GPIOB_NRST_3) | \
                                        PIN_OSPEED_HIGH(GPIOB_CO8) | \
                                        PIN_OSPEED_HIGH(GPIOB_NCS_MPU) | \
                                        PIN_OSPEED_HIGH(GPIOB_SPI2_SCK) | \
                                        PIN_OSPEED_HIGH(GPIOB_SPI2_MISO) | \
                                        PIN_OSPEED_HIGH(GPIOB_SPI2_MOSI))

#define VAL_GPIOB_PUPDR                (PIN_PUPD_PULLUP(GPIOB_PIN0) | \
                                        PIN_PUPD_PULLUP(GPIOB_PIN1) | \
                                        PIN_PUPD_FLOATING(GPIOB_NCS_3) | \
                                        PIN_PUPD_PULLDOWN(GPIOB_BC3) | \
                                        PIN_PUPD_PULLDOWN(GPIOB_BC1) | \
                                        PIN_PUPD_PULLDOWN(GPIOB_BC2) | \
                                        PIN_PUPD_PULLDOWN(GPIOB_BC4) | \
                                        PIN_PUPD_PULLDOWN(GPIOB_BC5) | \
                                        PIN_PUPD_PULLUP(GPIOB_PIN8) | \
                                        PIN_PUPD_PULLUP(GPIOB_PIN9) | \
                                        PIN_PUPD_FLOATING(GPIOB_NRST_3) | \
                                        PIN_PUPD_FLOATING(GPIOB_CO8) | \
                                        PIN_PUPD_FLOATING(GPIOB_NCS_MPU) | \
                                        PIN_PUPD_FLOATING(GPIOB_SPI2_SCK) | \
                                        PIN_PUPD_FLOATING(GPIOB_SPI2_MISO) | \
                                        PIN_PUPD_FLOATING(GPIOB_SPI2_MOSI))

#define VAL_GPIOB_ODR                  (PIN_OD_HIGH(GPIOB_PIN0) | \
                                        PIN_OD_HIGH(GPIOB_PIN1) | \
                                        PIN_OD_HIGH(GPIOB_NCS_3) | \
                                        PIN_OD_HIGH(GPIOB_BC3) | \
                                        PIN_OD_HIGH(GPIOB_BC1) | \
                                        PIN_OD_HIGH(GPIOB_BC2) | \
                                        PIN_OD_HIGH(GPIOB_BC4) | \
                                        PIN_OD_HIGH(GPIOB_BC5) | \
                                        PIN_OD_HIGH(GPIOB_PIN8) | \
                                        PIN_OD_HIGH(GPIOB_PIN9) | \
                                        PIN_OD_HIGH(GPIOB_NRST_3) | \
                                        PIN_OD_LOW(GPIOB_CO8) | \
                                        PIN_OD_HIGH(GPIOB_NCS_MPU) | \
                                        PIN_OD_HIGH(GPIOB_SPI2_SCK) | \
                                        PIN_OD_HIGH(GPIOB_SPI2_MISO) | \
                                        PIN_OD_HIGH(GPIOB_SPI2_MOSI))

#define VAL_GPIOB_AFRL                 (PIN_AFIO_AF(GPIOB_PIN0, 0U) | \
                                        PIN_AFIO_AF(GPIOB_PIN1, 0U) | \
                                        PIN_AFIO_AF(GPIOB_NCS_3, 0U) | \
                                        PIN_AFIO_AF(GPIOB_BC3, 0U) | \
                                        PIN_AFIO_AF(GPIOB_BC1, 0U) | \
                                        PIN_AFIO_AF(GPIOB_BC2, 0U) | \
                                        PIN_AFIO_AF(GPIOB_BC4, 0U) | \
                                        PIN_AFIO_AF(GPIOB_BC5, 0U))

#define VAL_GPIOB_AFRH                 (PIN_AFIO_AF(GPIOB_PIN8, 0U) | \
                                        PIN_AFIO_AF(GPIOB_PIN9, 0U) | \
                                        PIN_AFIO_AF(GPIOB_NRST_3, 0U) | \
                                        PIN_AFIO_AF(GPIOB_CO8, 0U) | \
                                        PIN_AFIO_AF(GPIOB_NCS_MPU, 0U) | \
                                        PIN_AFIO_AF(GPIOB_SPI2_SCK, 0U) | \
                                        PIN_AFIO_AF(GPIOB_SPI2_MISO, 0U) | \
                                        PIN_AFIO_AF(GPIOB_SPI2_MOSI, 0U))

/*
 *  GPIOC setup:
 *
 * PC0  - NCS_1                        (output floating).
 * PC1  - NRST_1                       (output floating).
 * PC2  - PIN2                         (unused).
 * PC3  - PIN3                         (unused).
 * PC4  - PIN4                         (unused).
 * PC5  - PIN5                         (unused).
 * PC6  - CO1                          (output startlow floating).
 * PC7  - CO2                          (output startlow floating).
 * PC8  - CO3                          (output startlow floating).
 * PC9  - CO4                          (output startlow floating).
 * PC10 - BR1                          (output startlow floating).
 * PC11 - PIN11                        (unused).
 * PC12 - PIN12                        (unused).
 * PC13 - LED_DIN                      (output startlow floating).
 * PC14 - CO7                          (output startlow floating).
 * PC15 - CO6                          (output startlow floating).
*/
#define VAL_GPIOC_MODER                (PIN_MODE_OUTPUT(GPIOC_NCS_1) | \
                                        PIN_MODE_OUTPUT(GPIOC_NRST_1) | \
                                        PIN_MODE_INPUT(GPIOC_PIN2) | \
                                        PIN_MODE_INPUT(GPIOC_PIN3) | \
                                        PIN_MODE_INPUT(GPIOC_PIN4) | \
                                        PIN_MODE_INPUT(GPIOC_PIN5) | \
                                        PIN_MODE_OUTPUT(GPIOC_CO1) | \
                                        PIN_MODE_OUTPUT(GPIOC_CO2) | \
                                        PIN_MODE_OUTPUT(GPIOC_CO3) | \
                                        PIN_MODE_OUTPUT(GPIOC_CO4) | \
                                        PIN_MODE_OUTPUT(GPIOC_BR1) | \
                                        PIN_MODE_INPUT(GPIOC_PIN11) | \
                                        PIN_MODE_INPUT(GPIOC_PIN12) | \
                                        PIN_MODE_OUTPUT(GPIOC_LED_DIN) | \
                                        PIN_MODE_OUTPUT(GPIOC_CO7) | \
                                        PIN_MODE_OUTPUT(GPIOC_CO6))

#define VAL_GPIOC_OTYPER               (PIN_OTYPE_PUSHPULL(GPIOC_NCS_1) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_NRST_1) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN2) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN3) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN4) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN5) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_CO1) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_CO2) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_CO3) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_CO4) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_BR1) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN11) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN12) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_LED_DIN) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_CO7) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_CO6))

#define VAL_GPIOC_OSPEEDR              (PIN_OSPEED_HIGH(GPIOC_NCS_1) | \
                                        PIN_OSPEED_HIGH(GPIOC_NRST_1) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN2) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN3) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN4) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN5) | \
                                        PIN_OSPEED_HIGH(GPIOC_CO1) | \
                                        PIN_OSPEED_HIGH(GPIOC_CO2) | \
                                        PIN_OSPEED_HIGH(GPIOC_CO3) | \
                                        PIN_OSPEED_HIGH(GPIOC_CO4) | \
                                        PIN_OSPEED_HIGH(GPIOC_BR1) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN11) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN12) | \
                                        PIN_OSPEED_HIGH(GPIOC_LED_DIN) | \
                                        PIN_OSPEED_HIGH(GPIOC_CO7) | \
                                        PIN_OSPEED_HIGH(GPIOC_CO6))

#define VAL_GPIOC_PUPDR                (PIN_PUPD_FLOATING(GPIOC_NCS_1) | \
                                        PIN_PUPD_FLOATING(GPIOC_NRST_1) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN2) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN3) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN4) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN5) | \
                                        PIN_PUPD_FLOATING(GPIOC_CO1) | \
                                        PIN_PUPD_FLOATING(GPIOC_CO2) | \
                                        PIN_PUPD_FLOATING(GPIOC_CO3) | \
                                        PIN_PUPD_FLOATING(GPIOC_CO4) | \
                                        PIN_PUPD_FLOATING(GPIOC_BR1) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN11) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN12) | \
                                        PIN_PUPD_FLOATING(GPIOC_LED_DIN) | \
                                        PIN_PUPD_FLOATING(GPIOC_CO7) | \
                                        PIN_PUPD_FLOATING(GPIOC_CO6))

#define VAL_GPIOC_ODR                  (PIN_OD_HIGH(GPIOC_NCS_1) | \
                                        PIN_OD_HIGH(GPIOC_NRST_1) | \
                                        PIN_OD_HIGH(GPIOC_PIN2) | \
                                        PIN_OD_HIGH(GPIOC_PIN3) | \
                                        PIN_OD_HIGH(GPIOC_PIN4) | \
                                        PIN_OD_HIGH(GPIOC_PIN5) | \
                                        PIN_OD_LOW(GPIOC_CO1) | \
                                        PIN_OD_LOW(GPIOC_CO2) | \
                                        PIN_OD_LOW(GPIOC_CO3) | \
                                        PIN_OD_LOW(GPIOC_CO4) | \
                                        PIN_OD_LOW(GPIOC_BR1) | \
                                        PIN_OD_HIGH(GPIOC_PIN11) | \
                                        PIN_OD_HIGH(GPIOC_PIN12) | \
                                        PIN_OD_LOW(GPIOC_LED_DIN) | \
                                        PIN_OD_LOW(GPIOC_CO7) | \
                                        PIN_OD_LOW(GPIOC_CO6))

#define VAL_GPIOC_AFRL                 (PIN_AFIO_AF(GPIOC_NCS_1, 0U) | \
                                        PIN_AFIO_AF(GPIOC_NRST_1, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN2, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN3, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN4, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN5, 0U) | \
                                        PIN_AFIO_AF(GPIOC_CO1, 0U) | \
                                        PIN_AFIO_AF(GPIOC_CO2, 0U))

#define VAL_GPIOC_AFRH                 (PIN_AFIO_AF(GPIOC_CO3, 0U) | \
                                        PIN_AFIO_AF(GPIOC_CO4, 0U) | \
                                        PIN_AFIO_AF(GPIOC_BR1, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN11, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN12, 0U) | \
                                        PIN_AFIO_AF(GPIOC_LED_DIN, 0U) | \
                                        PIN_AFIO_AF(GPIOC_CO7, 0U) | \
                                        PIN_AFIO_AF(GPIOC_CO6, 0U))

/*
 *  GPIOD setup:
 *
 * PD0  - PIN0                         (unused).
 * PD1  - PIN1                         (unused).
 * PD2  - PIN2                         (unused).
 * PD3  - PIN3                         (unused).
 * PD4  - PIN4                         (unused).
 * PD5  - PIN5                         (unused).
 * PD6  - PIN6                         (unused).
 * PD7  - PIN7                         (unused).
 * PD8  - PIN8                         (unused).
 * PD9  - PIN9                         (unused).
 * PD10 - PIN10                        (unused).
 * PD11 - PIN11                        (unused).
 * PD12 - PIN12                        (unused).
 * PD13 - PIN13                        (unused).
 * PD14 - PIN14                        (unused).
 * PD15 - PIN15                        (unused).
*/
#define VAL_GPIOD_MODER                (PIN_MODE_INPUT(GPIOD_PIN0) | \
                                        PIN_MODE_INPUT(GPIOD_PIN1) | \
                                        PIN_MODE_INPUT(GPIOD_PIN2) | \
                                        PIN_MODE_INPUT(GPIOD_PIN3) | \
                                        PIN_MODE_INPUT(GPIOD_PIN4) | \
                                        PIN_MODE_INPUT(GPIOD_PIN5) | \
                                        PIN_MODE_INPUT(GPIOD_PIN6) | \
                                        PIN_MODE_INPUT(GPIOD_PIN7) | \
                                        PIN_MODE_INPUT(GPIOD_PIN8) | \
                                        PIN_MODE_INPUT(GPIOD_PIN9) | \
                                        PIN_MODE_INPUT(GPIOD_PIN10) | \
                                        PIN_MODE_INPUT(GPIOD_PIN11) | \
                                        PIN_MODE_INPUT(GPIOD_PIN12) | \
                                        PIN_MODE_INPUT(GPIOD_PIN13) | \
                                        PIN_MODE_INPUT(GPIOD_PIN14) | \
                                        PIN_MODE_INPUT(GPIOD_PIN15))

#define VAL_GPIOD_OTYPER               (PIN_OTYPE_PUSHPULL(GPIOD_PIN0) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN1) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN2) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN3) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN4) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN5) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN6) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN7) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN8) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN9) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN10) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN11) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN12) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN13) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN14) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN15))

#define VAL_GPIOD_OSPEEDR              (PIN_OSPEED_HIGH(GPIOD_PIN0) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN1) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN2) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN3) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN4) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN5) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN6) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN7) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN8) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN9) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN10) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN11) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN12) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN13) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN14) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN15))

#define VAL_GPIOD_PUPDR                (PIN_PUPD_PULLUP(GPIOD_PIN0) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN1) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN2) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN3) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN4) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN5) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN6) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN7) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN8) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN9) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN10) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN11) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN12) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN13) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN14) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN15))

#define VAL_GPIOD_ODR                  (PIN_OD_HIGH(GPIOD_PIN0) | \
                                        PIN_OD_HIGH(GPIOD_PIN1) | \
                                        PIN_OD_HIGH(GPIOD_PIN2) | \
                                        PIN_OD_HIGH(GPIOD_PIN3) | \
                                        PIN_OD_HIGH(GPIOD_PIN4) | \
                                        PIN_OD_HIGH(GPIOD_PIN5) | \
                                        PIN_OD_HIGH(GPIOD_PIN6) | \
                                        PIN_OD_HIGH(GPIOD_PIN7) | \
                                        PIN_OD_HIGH(GPIOD_PIN8) | \
                                        PIN_OD_HIGH(GPIOD_PIN9) | \
                                        PIN_OD_HIGH(GPIOD_PIN10) | \
                                        PIN_OD_HIGH(GPIOD_PIN11) | \
                                        PIN_OD_HIGH(GPIOD_PIN12) | \
                                        PIN_OD_HIGH(GPIOD_PIN13) | \
                                        PIN_OD_HIGH(GPIOD_PIN14) | \
                                        PIN_OD_HIGH(GPIOD_PIN15))

#define VAL_GPIOD_AFRL                 (PIN_AFIO_AF(GPIOD_PIN0, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN1, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN2, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN3, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN4, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN5, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN6, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN7, 0U))

#define VAL_GPIOD_AFRH                 (PIN_AFIO_AF(GPIOD_PIN8, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN9, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN10, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN11, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN12, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN13, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN14, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN15, 0U))

/*
 *  GPIOE setup:
 *
 * PE0  - PIN0                         (unused).
 * PE1  - PIN1                         (unused).
 * PE2  - PIN2                         (unused).
 * PE3  - PIN3                         (unused).
 * PE4  - PIN4                         (unused).
 * PE5  - PIN5                         (unused).
 * PE6  - PIN6                         (unused).
 * PE7  - PIN7                         (unused).
 * PE8  - PIN8                         (unused).
 * PE9  - PIN9                         (unused).
 * PE10 - PIN10                        (unused).
 * PE11 - PIN11                        (unused).
 * PE12 - PIN12                        (unused).
 * PE13 - PIN13                        (unused).
 * PE14 - PIN14                        (unused).
 * PE15 - PIN15                        (unused).
*/
#define VAL_GPIOE_MODER                (PIN_MODE_INPUT(GPIOE_PIN0) | \
                                        PIN_MODE_INPUT(GPIOE_PIN1) | \
                                        PIN_MODE_INPUT(GPIOE_PIN2) | \
                                        PIN_MODE_INPUT(GPIOE_PIN3) | \
                                        PIN_MODE_INPUT(GPIOE_PIN4) | \
                                        PIN_MODE_INPUT(GPIOE_PIN5) | \
                                        PIN_MODE_INPUT(GPIOE_PIN6) | \
                                        PIN_MODE_INPUT(GPIOE_PIN7) | \
                                        PIN_MODE_INPUT(GPIOE_PIN8) | \
                                        PIN_MODE_INPUT(GPIOE_PIN9) | \
                                        PIN_MODE_INPUT(GPIOE_PIN10) | \
                                        PIN_MODE_INPUT(GPIOE_PIN11) | \
                                        PIN_MODE_INPUT(GPIOE_PIN12) | \
                                        PIN_MODE_INPUT(GPIOE_PIN13) | \
                                        PIN_MODE_INPUT(GPIOE_PIN14) | \
                                        PIN_MODE_INPUT(GPIOE_PIN15))

#define VAL_GPIOE_OTYPER               (PIN_OTYPE_PUSHPULL(GPIOE_PIN0) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_PIN1) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_PIN2) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_PIN3) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_PIN4) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_PIN5) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_PIN6) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_PIN7) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_PIN8) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_PIN9) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_PIN10) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_PIN11) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_PIN12) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_PIN13) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_PIN14) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_PIN15))

#define VAL_GPIOE_OSPEEDR              (PIN_OSPEED_HIGH(GPIOE_PIN0) | \
                                        PIN_OSPEED_HIGH(GPIOE_PIN1) | \
                                        PIN_OSPEED_HIGH(GPIOE_PIN2) | \
                                        PIN_OSPEED_HIGH(GPIOE_PIN3) | \
                                        PIN_OSPEED_HIGH(GPIOE_PIN4) | \
                                        PIN_OSPEED_HIGH(GPIOE_PIN5) | \
                                        PIN_OSPEED_HIGH(GPIOE_PIN6) | \
                                        PIN_OSPEED_HIGH(GPIOE_PIN7) | \
                                        PIN_OSPEED_HIGH(GPIOE_PIN8) | \
                                        PIN_OSPEED_HIGH(GPIOE_PIN9) | \
                                        PIN_OSPEED_HIGH(GPIOE_PIN10) | \
                                        PIN_OSPEED_HIGH(GPIOE_PIN11) | \
                                        PIN_OSPEED_HIGH(GPIOE_PIN12) | \
                                        PIN_OSPEED_HIGH(GPIOE_PIN13) | \
                                        PIN_OSPEED_HIGH(GPIOE_PIN14) | \
                                        PIN_OSPEED_HIGH(GPIOE_PIN15))

#define VAL_GPIOE_PUPDR                (PIN_PUPD_PULLUP(GPIOE_PIN0) | \
                                        PIN_PUPD_PULLUP(GPIOE_PIN1) | \
                                        PIN_PUPD_PULLUP(GPIOE_PIN2) | \
                                        PIN_PUPD_PULLUP(GPIOE_PIN3) | \
                                        PIN_PUPD_PULLUP(GPIOE_PIN4) | \
                                        PIN_PUPD_PULLUP(GPIOE_PIN5) | \
                                        PIN_PUPD_PULLUP(GPIOE_PIN6) | \
                                        PIN_PUPD_PULLUP(GPIOE_PIN7) | \
                                        PIN_PUPD_PULLUP(GPIOE_PIN8) | \
                                        PIN_PUPD_PULLUP(GPIOE_PIN9) | \
                                        PIN_PUPD_PULLUP(GPIOE_PIN10) | \
                                        PIN_PUPD_PULLUP(GPIOE_PIN11) | \
                                        PIN_PUPD_PULLUP(GPIOE_PIN12) | \
                                        PIN_PUPD_PULLUP(GPIOE_PIN13) | \
                                        PIN_PUPD_PULLUP(GPIOE_PIN14) | \
                                        PIN_PUPD_PULLUP(GPIOE_PIN15))

#define VAL_GPIOE_ODR                  (PIN_OD_HIGH(GPIOE_PIN0) | \
                                        PIN_OD_HIGH(GPIOE_PIN1) | \
                                        PIN_OD_HIGH(GPIOE_PIN2) | \
                                        PIN_OD_HIGH(GPIOE_PIN3) | \
                                        PIN_OD_HIGH(GPIOE_PIN4) | \
                                        PIN_OD_HIGH(GPIOE_PIN5) | \
                                        PIN_OD_HIGH(GPIOE_PIN6) | \
                                        PIN_OD_HIGH(GPIOE_PIN7) | \
                                        PIN_OD_HIGH(GPIOE_PIN8) | \
                                        PIN_OD_HIGH(GPIOE_PIN9) | \
                                        PIN_OD_HIGH(GPIOE_PIN10) | \
                                        PIN_OD_HIGH(GPIOE_PIN11) | \
                                        PIN_OD_HIGH(GPIOE_PIN12) | \
                                        PIN_OD_HIGH(GPIOE_PIN13) | \
                                        PIN_OD_HIGH(GPIOE_PIN14) | \
                                        PIN_OD_HIGH(GPIOE_PIN15))

#define VAL_GPIOE_AFRL                 (PIN_AFIO_AF(GPIOE_PIN0, 0U) | \
                                        PIN_AFIO_AF(GPIOE_PIN1, 0U) | \
                                        PIN_AFIO_AF(GPIOE_PIN2, 0U) | \
                                        PIN_AFIO_AF(GPIOE_PIN3, 0U) | \
                                        PIN_AFIO_AF(GPIOE_PIN4, 0U) | \
                                        PIN_AFIO_AF(GPIOE_PIN5, 0U) | \
                                        PIN_AFIO_AF(GPIOE_PIN6, 0U) | \
                                        PIN_AFIO_AF(GPIOE_PIN7, 0U))

#define VAL_GPIOE_AFRH                 (PIN_AFIO_AF(GPIOE_PIN8, 0U) | \
                                        PIN_AFIO_AF(GPIOE_PIN9, 0U) | \
                                        PIN_AFIO_AF(GPIOE_PIN10, 0U) | \
                                        PIN_AFIO_AF(GPIOE_PIN11, 0U) | \
                                        PIN_AFIO_AF(GPIOE_PIN12, 0U) | \
                                        PIN_AFIO_AF(GPIOE_PIN13, 0U) | \
                                        PIN_AFIO_AF(GPIOE_PIN14, 0U) | \
                                        PIN_AFIO_AF(GPIOE_PIN15, 0U))

/*
 *  GPIOF setup:
 *
 * PF0  - PIN0                         (unused).
 * PF1  - PIN1                         (unused).
 * PF2  - PIN2                         (unused).
 * PF3  - PIN3                         (unused).
 * PF4  - PIN4                         (unused).
 * PF5  - PIN5                         (unused).
 * PF6  - PIN6                         (unused).
 * PF7  - PIN7                         (unused).
 * PF8  - PIN8                         (unused).
 * PF9  - PIN9                         (unused).
 * PF10 - PIN10                        (unused).
 * PF11 - PIN11                        (unused).
 * PF12 - PIN12                        (unused).
 * PF13 - PIN13                        (unused).
 * PF14 - PIN14                        (unused).
 * PF15 - PIN15                        (unused).
*/
#define VAL_GPIOF_MODER                (PIN_MODE_INPUT(GPIOF_PIN0) | \
                                        PIN_MODE_INPUT(GPIOF_PIN1) | \
                                        PIN_MODE_INPUT(GPIOF_PIN2) | \
                                        PIN_MODE_INPUT(GPIOF_PIN3) | \
                                        PIN_MODE_INPUT(GPIOF_PIN4) | \
                                        PIN_MODE_INPUT(GPIOF_PIN5) | \
                                        PIN_MODE_INPUT(GPIOF_PIN6) | \
                                        PIN_MODE_INPUT(GPIOF_PIN7) | \
                                        PIN_MODE_INPUT(GPIOF_PIN8) | \
                                        PIN_MODE_INPUT(GPIOF_PIN9) | \
                                        PIN_MODE_INPUT(GPIOF_PIN10) | \
                                        PIN_MODE_INPUT(GPIOF_PIN11) | \
                                        PIN_MODE_INPUT(GPIOF_PIN12) | \
                                        PIN_MODE_INPUT(GPIOF_PIN13) | \
                                        PIN_MODE_INPUT(GPIOF_PIN14) | \
                                        PIN_MODE_INPUT(GPIOF_PIN15))

#define VAL_GPIOF_OTYPER               (PIN_OTYPE_PUSHPULL(GPIOF_PIN0) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN1) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN2) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN3) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN4) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN5) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN6) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN7) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN8) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN9) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN10) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN11) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN12) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN13) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN14) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN15))

#define VAL_GPIOF_OSPEEDR              (PIN_OSPEED_HIGH(GPIOF_PIN0) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN1) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN2) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN3) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN4) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN5) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN6) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN7) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN8) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN9) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN10) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN11) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN12) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN13) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN14) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN15))

#define VAL_GPIOF_PUPDR                (PIN_PUPD_PULLUP(GPIOF_PIN0) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN1) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN2) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN3) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN4) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN5) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN6) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN7) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN8) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN9) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN10) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN11) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN12) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN13) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN14) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN15))

#define VAL_GPIOF_ODR                  (PIN_OD_HIGH(GPIOF_PIN0) | \
                                        PIN_OD_HIGH(GPIOF_PIN1) | \
                                        PIN_OD_HIGH(GPIOF_PIN2) | \
                                        PIN_OD_HIGH(GPIOF_PIN3) | \
                                        PIN_OD_HIGH(GPIOF_PIN4) | \
                                        PIN_OD_HIGH(GPIOF_PIN5) | \
                                        PIN_OD_HIGH(GPIOF_PIN6) | \
                                        PIN_OD_HIGH(GPIOF_PIN7) | \
                                        PIN_OD_HIGH(GPIOF_PIN8) | \
                                        PIN_OD_HIGH(GPIOF_PIN9) | \
                                        PIN_OD_HIGH(GPIOF_PIN10) | \
                                        PIN_OD_HIGH(GPIOF_PIN11) | \
                                        PIN_OD_HIGH(GPIOF_PIN12) | \
                                        PIN_OD_HIGH(GPIOF_PIN13) | \
                                        PIN_OD_HIGH(GPIOF_PIN14) | \
                                        PIN_OD_HIGH(GPIOF_PIN15))

#define VAL_GPIOF_AFRL                 (PIN_AFIO_AF(GPIOF_PIN0, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN1, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN2, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN3, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN4, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN5, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN6, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN7, 0U))

#define VAL_GPIOF_AFRH                 (PIN_AFIO_AF(GPIOF_PIN8, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN9, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN10, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN11, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN12, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN13, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN14, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN15, 0U))

#if !defined(_FROM_ASM_)
#ifdef __cplusplus
extern "C" {
#endif
  void boardInit(void);
#ifdef __cplusplus
}
#endif
#endif /* _FROM_ASM_ */

#endif /* _BOARD_H_ */